version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: patrikjuvonen/docker-nginx-http3:nginx-quic
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
